export interface PlanetData {
  id: string;
  name: string;
  nickname: string;
  diameter: string;
  gravity: string;
  atmosphere: string;
  temperature: string;
  dayLength: string;
  yearLength: string;
  moons: number;
  funFact: string;
  missions: string[];
  description: string;
  color: string;
  habitability: number; // 0 to 100
  distanceFromSun: number; // AU
  orbitalSpeed: number; // relative
  size: number; // relative for 3D
}

export const PLANETS: PlanetData[] = [
  {
    id: "mercury",
    name: "Mercury",
    nickname: "The Swift Planet",
    diameter: "4,879 km",
    gravity: "3.7 m/s²",
    atmosphere: "Thin (Oxygen, Sodium, Hydrogen)",
    temperature: "-173°C to 427°C",
    dayLength: "59 Earth days",
    yearLength: "88 Earth days",
    moons: 0,
    funFact: "Mercury is shrinking as its iron core cools.",
    missions: ["Mariner 10", "MESSENGER", "BepiColombo"],
    description: "The smallest and innermost planet, Mercury is a sun-scorched world of extremes.",
    color: "#A5A5A5",
    habitability: 5,
    distanceFromSun: 0.39,
    orbitalSpeed: 4.1,
    size: 0.38,
  },
  {
    id: "venus",
    name: "Venus",
    nickname: "Earth's Evil Twin",
    diameter: "12,104 km",
    gravity: "8.87 m/s²",
    atmosphere: "Thick (Carbon Dioxide, Nitrogen)",
    temperature: "462°C (Average)",
    dayLength: "243 Earth days",
    yearLength: "225 Earth days",
    moons: 0,
    funFact: "Venus rotates backward on its axis compared to other planets.",
    missions: ["Venera", "Magellan", "Akatsuki"],
    description: "A runaway greenhouse effect makes Venus the hottest planet in our solar system.",
    color: "#E3BB76",
    habitability: 2,
    distanceFromSun: 0.72,
    orbitalSpeed: 1.6,
    size: 0.95,
  },
  {
    id: "earth",
    name: "Earth",
    nickname: "The Blue Marble",
    diameter: "12,742 km",
    gravity: "9.81 m/s²",
    atmosphere: "Nitrogen, Oxygen",
    temperature: "-89°C to 58°C",
    dayLength: "24 hours",
    yearLength: "365 days",
    moons: 1,
    funFact: "Earth is the only known planet to support life.",
    missions: ["Apollo", "ISS", "Voyager"],
    description: "Our home, a vibrant oasis of water and life in the vast darkness of space.",
    color: "#2271B3",
    habitability: 100,
    distanceFromSun: 1.0,
    orbitalSpeed: 1.0,
    size: 1.0,
  },
  {
    id: "mars",
    name: "Mars",
    nickname: "The Red Planet",
    diameter: "6,779 km",
    gravity: "3.71 m/s²",
    atmosphere: "Thin (Carbon Dioxide, Nitrogen)",
    temperature: "-153°C to 20°C",
    dayLength: "24.6 hours",
    yearLength: "687 Earth days",
    moons: 2,
    funFact: "Mars is home to Olympus Mons, the largest volcano in the solar system.",
    missions: ["Curiosity", "Perseverance", "Mariner"],
    description: "A dusty, cold, desert world with a thin atmosphere and polar ice caps.",
    color: "#E27B58",
    habitability: 45,
    distanceFromSun: 1.52,
    orbitalSpeed: 0.5,
    size: 0.53,
  },
  {
    id: "jupiter",
    name: "Jupiter",
    nickname: "King of the Planets",
    diameter: "139,820 km",
    gravity: "24.79 m/s²",
    atmosphere: "Hydrogen, Helium",
    temperature: "-110°C",
    dayLength: "9.9 hours",
    yearLength: "11.8 Earth years",
    moons: 95,
    funFact: "Jupiter's Great Red Spot is a storm that has lasted for centuries.",
    missions: ["Galileo", "Juno", "Voyager"],
    description: "The most massive planet, a gas giant that could fit 1,300 Earths inside.",
    color: "#D39C7E",
    habitability: 0,
    distanceFromSun: 5.2,
    orbitalSpeed: 0.08,
    size: 2.5,
  },
  {
    id: "saturn",
    name: "Saturn",
    nickname: "Jewel of the Solar System",
    diameter: "116,460 km",
    gravity: "10.44 m/s²",
    atmosphere: "Hydrogen, Helium",
    temperature: "-140°C",
    dayLength: "10.7 hours",
    yearLength: "29.4 Earth years",
    moons: 146,
    funFact: "Saturn could float in water because it is mostly made of gas.",
    missions: ["Cassini", "Pioneer 11", "Voyager"],
    description: "Famous for its spectacular ring system made of ice and rock fragments.",
    color: "#C5AB6E",
    habitability: 0,
    distanceFromSun: 9.5,
    orbitalSpeed: 0.03,
    size: 2.1,
  },
  {
    id: "uranus",
    name: "Uranus",
    nickname: "The Sideways Planet",
    diameter: "50,724 km",
    gravity: "8.69 m/s²",
    atmosphere: "Hydrogen, Helium, Methane",
    temperature: "-195°C",
    dayLength: "17.2 hours",
    yearLength: "84 Earth years",
    moons: 27,
    funFact: "Uranus orbits the Sun on its side, tilted 98 degrees.",
    missions: ["Voyager 2"],
    description: "An ice giant with a pale blue-green color due to methane in its atmosphere.",
    color: "#B5E3E3",
    habitability: 0,
    distanceFromSun: 19.2,
    orbitalSpeed: 0.01,
    size: 1.2,
  },
  {
    id: "neptune",
    name: "Neptune",
    nickname: "The Windy Planet",
    diameter: "49,244 km",
    gravity: "11.15 m/s²",
    atmosphere: "Hydrogen, Helium, Methane",
    temperature: "-201°C",
    dayLength: "16.1 hours",
    yearLength: "165 Earth years",
    moons: 14,
    funFact: "Neptune was the first planet located through mathematical calculations.",
    missions: ["Voyager 2"],
    description: "The most distant major planet, a dark, cold, and whipped by supersonic winds.",
    color: "#4B70DD",
    habitability: 0,
    distanceFromSun: 30.1,
    orbitalSpeed: 0.006,
    size: 1.2,
  },
];

export const SPACE_WONDERS = [
  {
    name: "Asteroid Belt",
    description: "A vast region between Mars and Jupiter filled with rocky remnants from the early solar system.",
    icon: "Asteroids",
  },
  {
    name: "Pluto",
    description: "The most famous dwarf planet, once considered the ninth planet until its reclassification in 2006.",
    icon: "DwarfPlanet",
  },
  {
    name: "Black Holes",
    description: "Regions of spacetime where gravity is so strong that nothing, not even light, can escape.",
    icon: "Vortex",
  },
  {
    name: "Comets",
    description: "Icy bodies that release gas or dust, often called 'dirty snowballs' of the solar system.",
    icon: "Comet",
  },
  {
    name: "Exoplanets",
    description: "Planets orbiting stars outside our solar system, with over 5,000 discovered to date.",
    icon: "Exoplanet",
  },
];
